name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up the SSH agent and add the SSH key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Add the server to known_hosts to prevent SSH from prompting to verify the host
      - name: Add Server to known_hosts
        run: |
          ssh-keyscan -H 67.207.87.95 >> ~/.ssh/known_hosts

      # 4. Deploy to the server
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no telegrambot@67.207.87.95 << 'EOF'
            cd /home/telegrambot/CBTherapyBot
            
            git fetch origin main
            git reset --hard origin/main 
            source venv/bin/activate
            pip install -r requirements.txt
            sudo /usr/bin/systemctl restart cbtherapybot.service
          EOF

      # 5. (Optional) Upload Deployment Logs for Debugging
      - name: Upload Deployment Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: deployment-log
          path: deploy.log
